# Generated by Django 5.0.2 on 2024-05-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='occasion/'),
        ),
    ]
